// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpJ3z8BQgIsh-uHh10HRYb5ibpHx7jps',
    appId: '1:485553656526:web:8e567c08b15d8eb205f69f',
    messagingSenderId: '485553656526',
    projectId: 'toi-hoc-fullter-mynotes',
    authDomain: 'toi-hoc-fullter-mynotes.firebaseapp.com',
    storageBucket: 'toi-hoc-fullter-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEsVI8lJankm2PGDuQHxChLC0HFATFYQ',
    appId: '1:485553656526:android:ab033b463a83978b05f69f',
    messagingSenderId: '485553656526',
    projectId: 'toi-hoc-fullter-mynotes',
    storageBucket: 'toi-hoc-fullter-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FFLLjbySdaam_S1WKigCeWI5fAg8mf8',
    appId: '1:485553656526:ios:7f39dcdd977c242805f69f',
    messagingSenderId: '485553656526',
    projectId: 'toi-hoc-fullter-mynotes',
    storageBucket: 'toi-hoc-fullter-mynotes.appspot.com',
    iosClientId: '485553656526-ij2k9gpbrr59vu83rq3pa1n6rdnpeqgj.apps.googleusercontent.com',
    iosBundleId: 'learn.flutter.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FFLLjbySdaam_S1WKigCeWI5fAg8mf8',
    appId: '1:485553656526:ios:05f43199608173b405f69f',
    messagingSenderId: '485553656526',
    projectId: 'toi-hoc-fullter-mynotes',
    storageBucket: 'toi-hoc-fullter-mynotes.appspot.com',
    iosClientId: '485553656526-shr5pbisasntms9ldcavbsvucupen9l9.apps.googleusercontent.com',
    iosBundleId: 'learn.flutter.mynotes.RunnerTests',
  );
}
